name: brew test-bot
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-bot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: homebrew/actions/setup-homebrew@master
        working-directory: /usr/local/Homebrew/Library/Taps/stephan-hesselmann-by/homebrew-blueyonder
        run: |
          brew test-bot
