name: update-tap

on:
  schedule:
    # Run every hour
    - cron:  '0 * * * *'

jobs:
  update-tap:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tap: by-stehessel/BlueYonder
          force: false
          livecheck: true
