name: update-tap

on:
  schedule:
    # Run every hour
    - cron:  '0 * * * *'

jobs:
  update-tap:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3.1
        with:
          # Requires personal access token
          token: "${{ secrets.TOKEN }}"
          tap: stephan-hesselmann-by/BlueYonder
          force: false
          livecheck: true
